// Code generated by "rpctocli "; DO NOT EDIT
package main

import(
	"github.com/codegangsta/cli"
)

var ArithCommand = cli.Command{Name: "Arith",Subcommands: []cli.Command{MultiplySubCommand, TestSubCommand, DivideSubCommand, },}

var DivideSubCommand = cli.Command{Name: "Divide",Flags: []cli.Flag{}, Action: func(ctx *cli.Context) {},}

var MultiplySubCommand = cli.Command{Name: "Multiply",Flags: []cli.Flag{}, Action: func(ctx *cli.Context) {},}

var TestSubCommand = cli.Command{Name: "Test",Flags: []cli.Flag{}, Action: func(ctx *cli.Context) {},}

var GeneratedCommands = []cli.Command{ArithCommand, }